import express from "express";
import { protect, authorize } from "../middleware/authMiddleware.js";
import { getCompanies, getCompanyById, getRecruiterCompanies, createCompany, updateCompany, deleteCompany } from "../controllers/companyController.js";
import upload from "../middleware/upload.js";
const router = express.Router();
router.get("/", getCompanies);
router.get("/recruiter/mine", protect, authorize("recruiter"), getRecruiterCompanies);
router.get("/:id", getCompanyById);
router.post("/", protect, authorize("recruiter"), upload.fields([{ name: "logo", maxCount: 1 }]), createCompany);
router.put("/:id", protect, authorize("recruiter"), upload.fields([{ name: "logo", maxCount: 1 }]), updateCompany);
router.delete("/:id", protect, authorize("recruiter"), deleteCompany);
export default router;
