import React from "react";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { Ionicons } from "@expo/vector-icons";
import { useAuth } from "../context/AuthContext";
import { colors } from "../theme/theme";
import Home from "../screens/Home";import Pricing from "../screens/Pricing";import Jobs from "../screens/Jobs";import JobDetails from "../screens/JobDetails";import Companies from "../screens/Companies";import CompanyDetails from "../screens/CompanyDetails";import Login from "../screens/Login";import Register from "../screens/Register";import ForgotPassword from "../screens/ForgotPassword";import ResetPassword from "../screens/ResetPassword";import VerifyOTP from "../screens/VerifyOTP";import About from "../screens/About";import Contact from "../screens/Contact";
import CandidateDashboard from "../screens/CandidateDashboard";import CandidateProfile from "../screens/CandidateProfile";import CandidateApplications from "../screens/CandidateApplications";import CandidateFavorites from "../screens/CandidateFavorites";
import RecruiterDashboard from "../screens/RecruiterDashboard";import RecruiterJobs from "../screens/RecruiterJobs";import PostJob from "../screens/PostJob";import RecruiterApplications from "../screens/RecruiterApplications";import RecruiterProfile from "../screens/RecruiterProfile";import CandidateSearch from "../screens/CandidateSearch";import CvPackages from "../screens/CvPackages";import CompanyManager from "../screens/CompanyManager";import ViewApplication from "../screens/ViewApplication";
import Notifications from "../screens/Notifications";
import AdminDashboard from "../screens/AdminDashboard";import AdminResource from "../screens/AdminResource";import AdminMenu from "../screens/AdminMenu";import AdminTool from "../screens/AdminTool";
const Stack=createNativeStackNavigator(),Tabs=createBottomTabNavigator(),opts={headerShown:false};
const icon=(name)=>(props)=><Ionicons name={name} size={props.size} color={props.color}/>;
function PublicTabs(){return <Tabs.Navigator screenOptions={({route})=>({headerShown:false,tabBarActiveTintColor:colors.primary,tabBarLabelStyle:{fontSize:11},tabBarIcon:icon({Home:"home-outline",Jobs:"briefcase-outline",Companies:"business-outline"}[route.name])})}><Tabs.Screen name="Home" component={Home}/><Tabs.Screen name="Jobs" component={Jobs}/><Tabs.Screen name="Companies" component={Companies}/></Tabs.Navigator>}
function CandidateTabs(){return <Tabs.Navigator screenOptions={{headerShown:false,tabBarActiveTintColor:colors.primary,tabBarLabelStyle:{fontSize:10}}}><Tabs.Screen name="Dashboard" component={CandidateDashboard} options={{tabBarIcon:icon("grid-outline")}}/><Tabs.Screen name="Jobs" component={Jobs} options={{tabBarIcon:icon("search-outline")}}/><Tabs.Screen name="Applications" component={CandidateApplications} options={{tabBarIcon:icon("document-text-outline")}}/><Tabs.Screen name="Favorites" component={CandidateFavorites} options={{tabBarIcon:icon("heart-outline")}}/><Tabs.Screen name="Profile" component={CandidateProfile} options={{tabBarIcon:icon("person-outline")}}/></Tabs.Navigator>}
function RecruiterTabs(){return <Tabs.Navigator screenOptions={{headerShown:false,tabBarActiveTintColor:colors.primary,tabBarLabelStyle:{fontSize:9}}}><Tabs.Screen name="Dashboard" component={RecruiterDashboard} options={{tabBarIcon:icon("grid-outline")}}/><Tabs.Screen name="Jobs" component={RecruiterJobs} options={{tabBarIcon:icon("briefcase-outline")}}/><Tabs.Screen name="Applications" component={RecruiterApplications} options={{tabBarIcon:icon("people-outline")}}/><Tabs.Screen name="Candidates" component={CandidateSearch} options={{tabBarIcon:icon("search-outline")}}/><Tabs.Screen name="Profile" component={RecruiterProfile} options={{tabBarIcon:icon("person-outline")}}/></Tabs.Navigator>}
function AdminTabs(){return <Tabs.Navigator screenOptions={{headerShown:false,tabBarActiveTintColor:colors.primary,tabBarLabelStyle:{fontSize:9}}}><Tabs.Screen name="Dashboard" component={AdminDashboard} options={{tabBarIcon:icon("grid-outline")}}/><Tabs.Screen name="Users" children={()=> <AdminResource resource="users" title="Users"/>} options={{tabBarIcon:icon("people-outline")}}/><Tabs.Screen name="Jobs" children={()=> <AdminResource resource="jobs" title="Jobs"/>} options={{tabBarIcon:icon("briefcase-outline")}}/><Tabs.Screen name="Applications" children={()=> <AdminResource resource="applications" title="Applications"/>} options={{tabBarIcon:icon("document-text-outline")}}/><Tabs.Screen name="More" component={AdminMenu} options={{tabBarIcon:icon("settings-outline")}}/></Tabs.Navigator>}
export default function RootNavigator(){const{user,loading}=useAuth();if(loading)return null;return <Stack.Navigator screenOptions={opts}>{!user?<><Stack.Screen name="Public" component={PublicTabs}/><Stack.Screen name="Login" component={Login}/><Stack.Screen name="Register" component={Register}/><Stack.Screen name="ForgotPassword" component={ForgotPassword}/><Stack.Screen name="ResetPassword" component={ResetPassword}/><Stack.Screen name="VerifyOTP" component={VerifyOTP}/><Stack.Screen name="JobDetails" component={JobDetails}/><Stack.Screen name="CompanyDetails" component={CompanyDetails}/><Stack.Screen name="About" component={About}/><Stack.Screen name="Contact" component={Contact}/></>:user.role==="jobseeker"?<><Stack.Screen name="Candidate" component={CandidateTabs}/><Stack.Screen name="Notifications" component={Notifications}/><Stack.Screen name="JobDetails" component={JobDetails}/><Stack.Screen name="CompanyDetails" component={CompanyDetails}/></>:user.role==="recruiter"?<><Stack.Screen name="Recruiter" component={RecruiterTabs}/><Stack.Screen name="Notifications" component={Notifications}/><Stack.Screen name="PostJob" component={PostJob}/><Stack.Screen name="ViewApplication" component={ViewApplication}/><Stack.Screen name="CvPackages" component={CvPackages}/><Stack.Screen name="CompanyManager" component={CompanyManager}/><Stack.Screen name="JobDetails" component={JobDetails}/></>:<><Stack.Screen name="Admin" component={AdminTabs}/><Stack.Screen name="Notifications" component={Notifications}/><Stack.Screen name="AdminResource" component={AdminResource}/><Stack.Screen name="AdminMenu" component={AdminMenu}/><Stack.Screen name="AdminTool" component={AdminTool}/><Stack.Screen name="JobDetails" component={JobDetails}/></>}</Stack.Navigator>}
